import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { google } from '@ai-sdk/google';
import { generateText } from 'ai';

// Colores ANSI para una salida premium en terminal
const colors = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  magenta: '\x1b[35m'
};

interface Issue {
  type: 'spelling' | 'grammar' | 'seo' | 'geo' | 'style';
  severity: 'error' | 'warning';
  line: number;
  original: string;
  replacement: string;
  explanation: string;
}

interface FileReport {
  filePath: string;
  isValid: boolean;
  issues: Issue[];
}

// 1. Cargar variables de entorno manualmente desde .env
function loadEnv() {
  const envPath = path.resolve(process.cwd(), '.env');
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const match = trimmed.match(/^([\w.-]+)\s*=\s*(.*)?$/);
      if (match) {
        const key = match[1];
        let value = match[2] || '';
        // Limpiar comillas
        if (value.startsWith('"') && value.endsWith('"')) {
          value = value.slice(1, -1);
        } else if (value.startsWith("'") && value.endsWith("'")) {
          value = value.slice(1, -1);
        }
        process.env[key] = value;
      }
    }
  }
  
  // Mapear GEMINI_API_KEY a la variable que espera el SDK de Google
  if (process.env.GEMINI_API_KEY && !process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
    process.env.GOOGLE_GENERATIVE_AI_API_KEY = process.env.GEMINI_API_KEY;
  }
}

// 2. Obtener archivos modificados por Git
function getChangedFiles(): string[] {
  try {
    const stdout = execSync('git status --porcelain', { encoding: 'utf8' });
    if (!stdout.trim()) return [];
    
    return stdout
      .split('\n')
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => {
        const status = line.slice(0, 2).trim();
        let filePath = line.slice(2).trim();
        // Manejar renombrados (ej. R old -> new)
        if (status.startsWith('R')) {
          const parts = filePath.split(' -> ');
          filePath = parts[parts.length - 1].trim();
        }
        // Limpiar comillas si las hay
        if (filePath.startsWith('"') && filePath.endsWith('"')) {
          filePath = filePath.slice(1, -1);
        }
        return filePath;
      });
  } catch (error) {
    console.error(`${colors.yellow}Advertencia: No se pudo ejecutar git status. Escaneando archivos principales por defecto.${colors.reset}`);
    return [];
  }
}

// 3. Obtener todos los archivos relevantes en caso de no haber cambios en Git
function getAllProjectFiles(dir: string = 'src'): string[] {
  let results: string[] = [];
  if (!fs.existsSync(dir)) return results;
  
  const list = fs.readdirSync(dir);
  for (const file of list) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(getAllProjectFiles(filePath));
    } else {
      const ext = path.extname(filePath);
      if (['.ts', '.tsx', '.md', '.mdx', '.js', '.jsx'].includes(ext)) {
        results.push(filePath);
      }
    }
  }
  return results;
}

// 4. Analizar un archivo con Gemini
async function analyzeFile(filePath: string): Promise<FileReport> {
  const content = fs.readFileSync(filePath, 'utf8');
  
  const prompt = `
Analiza el siguiente archivo del proyecto para verificar la calidad lingüística en español de España (Castellano), las mejores prácticas de SEO y la optimización para buscadores de IA (GEO).

Nombre del archivo: ${filePath}
Contenido del archivo:
"""
${content}
"""

Debes verificar estrictamente:
1. Ortografía y gramática en español de España (Castellano):
   - Uso correcto de tildes (acentuación, ej. "comunicación", "diseño", "imágenes").
   - Conjugación correcta de verbos y concordancia de género y número.
   - Expresiones y términos naturales de España (ej. "ordenador" en lugar de "computadora", "móvil" en lugar de "celular").
2. Buenas prácticas de SEO y GEO (AI Search Engine Optimization):
   - Evitar valores por defecto de Next.js (como "Create Next App", "Generated by create next app" o "lang=\\"en\\"" en lugar de "lang=\\"es\\"").
   - Jerarquía de encabezados coherente (un solo H1 principal, orden lógico H2, H3).
   - Presencia de atributos 'alt' significativos en etiquetas de imágenes.
   - Marcado estructurado (JSON-LD) si es una página o layout principal.

Devuelve tu análisis en formato JSON estructurado EXACTAMENTE como se muestra a continuación, sin explicaciones externas, sin etiquetas de código adicionales (solo devuelve el objeto JSON puro o dentro de un bloque de código markdown \`\`\`json):

{
  "isValid": true,
  "issues": [
    {
      "type": "spelling", // puede ser: "spelling", "grammar", "seo", "geo", "style"
      "severity": "error", // "error" (bloqueante) o "warning" (advertencia)
      "line": 12, // número de línea aproximado donde está el problema
      "original": "texto con el error",
      "replacement": "texto corregido sugerido",
      "explanation": "Explicación de por qué está mal y cómo se corrige."
    }
  ]
}
`;

  try {
    const model = google('gemini-2.5-flash'); // Usar Gemini 2.5 Flash
    const { text } = await generateText({
      model,
      prompt,
      temperature: 0.1,
    });

    // Extraer JSON si viene envuelto en markdown
    let jsonText = text.trim();
    const jsonMatch = jsonText.match(/```json\s*([\s\S]*?)\s*```/) || jsonText.match(/```\s*([\s\S]*?)\s*```/);
    if (jsonMatch) {
      jsonText = jsonMatch[1].trim();
    }

    const parsed = JSON.parse(jsonText) as { isValid: boolean; issues: Issue[] };
    return {
      filePath,
      isValid: parsed.isValid,
      issues: parsed.issues || []
    };
  } catch (error) {
    return {
      filePath,
      isValid: false,
      issues: [
        {
          type: 'style',
          severity: 'warning',
          line: 0,
          original: '',
          replacement: '',
          explanation: `Error al procesar el archivo con la IA: ${(error as Error).message}`
        }
      ]
    };
  }
}

// 5. Función principal
async function main() {
  loadEnv();
  
  console.log(`${colors.bold}${colors.cyan}====================================================`);
  console.log(`🤖 AGENTE DE VALIDACIÓN PRE-DEPLOY (SEO, GEO & ORTOGRAFÍA)`);
  console.log(`====================================================${colors.reset}\n`);

  if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
    console.error(`${colors.red}${colors.bold}Error: No se encontró GEMINI_API_KEY en el archivo .env.${colors.reset}`);
    console.error(`Por favor, añade tu clave al archivo .env para poder continuar.\n`);
    process.exit(1);
  }

  // Detectar archivos
  let filesToAnalyze = getChangedFiles();
  
  // Filtrar tipos de archivo de interés
  filesToAnalyze = filesToAnalyze.filter(file => {
    const ext = path.extname(file);
    const isCodeOrDoc = ['.ts', '.tsx', '.md', '.mdx', '.js', '.jsx'].includes(ext);
    const isNotConfig = !file.includes('next.config') && !file.includes('eslint') && !file.includes('tailwind.config') && !file.includes('tsconfig');
    const isNotNodeModules = !file.startsWith('node_modules') && !file.startsWith('.next');
    return isCodeOrDoc && isNotConfig && isNotNodeModules;
  });

  if (filesToAnalyze.length === 0) {
    console.log(`${colors.yellow}No se detectaron archivos modificados en Git. Escaneando la carpeta 'src' al completo...${colors.reset}\n`);
    filesToAnalyze = getAllProjectFiles('src');
  }

  if (filesToAnalyze.length === 0) {
    console.log(`${colors.green}✔ No hay archivos para analizar.${colors.reset}`);
    process.exit(0);
  }

  console.log(`Archivos a analizar (${filesToAnalyze.length}):`);
  filesToAnalyze.forEach(file => console.log(`  - ${file}`));
  console.log('\n⌛ Analizando cambios con Gemini...');

  let hasErrors = false;
  let totalIssues = 0;
  const reports: FileReport[] = [];

  for (const file of filesToAnalyze) {
    process.stdout.write(`  Análisis de ${file}... `);
    const report = await analyzeFile(file);
    reports.push(report);

    if (report.isValid && report.issues.length === 0) {
      console.log(`${colors.green}✔ Todo correcto${colors.reset}`);
    } else {
      const errors = report.issues.filter(i => i.severity === 'error');
      const warnings = report.issues.filter(i => i.severity === 'warning');
      
      if (errors.length > 0) {
        console.log(`${colors.red}✘ Encontrados ${errors.length} errores${colors.reset}`);
        hasErrors = true;
      } else {
        console.log(`${colors.yellow}⚠ Encontradas ${warnings.length} advertencias${colors.reset}`);
      }
      totalIssues += report.issues.length;
    }
  }

  // 6. Validaciones estructurales del proyecto
  console.log(`\n⌛ Ejecutando validaciones estructurales de GEO/AI...`);
  
  // Validar llms.txt
  const llmsPath = path.resolve(process.cwd(), 'public', 'llms.txt');
  if (!fs.existsSync(llmsPath)) {
    console.log(`${colors.yellow}⚠ GEO Warning: El archivo 'public/llms.txt' no existe. Es recomendable para que rastreadores de IA conozcan tu sitio.${colors.reset}`);
    totalIssues++;
  } else {
    const llmsContent = fs.readFileSync(llmsPath, 'utf8');
    if (llmsContent.length < 150) {
      console.log(`${colors.yellow}⚠ GEO Warning: El archivo 'public/llms.txt' es muy corto (${llmsContent.length} bytes). Considera enriquecerlo con descripciones de tus páginas y arquitectura.${colors.reset}`);
      totalIssues++;
    } else {
      console.log(`${colors.green}✔ public/llms.txt presente y bien dimensionado.${colors.reset}`);
    }
  }

  // Imprimir resumen detallado de problemas
  if (totalIssues > 0) {
    console.log(`\n${colors.bold}${colors.red}================ DETALLE DE DETECCIONES ================${colors.reset}`);
    for (const report of reports) {
      if (report.issues.length === 0) continue;
      
      console.log(`\n${colors.bold}${colors.cyan}Archivo: [${report.filePath}]${colors.reset}`);
      for (const issue of report.issues) {
        const prefix = issue.severity === 'error' 
          ? `${colors.red}[ERROR]` 
          : `${colors.yellow}[WARNING]`;
          
        console.log(`  ${prefix} (Línea ${issue.line || 'N/A'}) - Tipo: ${issue.type.toUpperCase()}`);
        console.log(`    Encontrado: "${colors.red}${issue.original}${colors.reset}"`);
        console.log(`    Sugerencia: "${colors.green}${issue.replacement}${colors.reset}"`);
        console.log(`    Explicación: ${issue.explanation}`);
      }
    }
    console.log(`\n${colors.bold}${colors.red}========================================================${colors.reset}`);
  }

  console.log(`\n====================================================`);
  console.log(`RESUMEN FINAL:`);
  console.log(`  - Archivos analizados: ${filesToAnalyze.length}`);
  console.log(`  - Total de problemas encontrados: ${totalIssues}`);
  console.log(`====================================================`);

  if (hasErrors) {
    console.log(`\n${colors.red}${colors.bold}❌ VALIDACIÓN FALLIDA: Hay errores graves que bloquean el despliegue.${colors.reset}`);
    console.log(`Por favor, corrige los problemas señalados arriba antes de subir los cambios.\n`);
    process.exit(1);
  } else {
    console.log(`\n${colors.green}${colors.bold}✔ VALIDACIÓN EXITOSA: Los cambios cumplen con los estándares de calidad.${colors.reset}\n`);
    process.exit(0);
  }
}

main().catch(err => {
  console.error(`\nError fatal en el agente:`, err);
  process.exit(1);
});
